name = "usaa-pilot-tracker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "USAA_PILOTS"
id = "47bc476c9bb04bdea4a4eb5424122e60"
preview_id = "fbffca54ee214babb24f933f7873c772"

[build]
command = ""

[env.development]
name = "usaa-pilot-tracker-dev"

[[env.development.kv_namespaces]]
binding = "USAA_PILOTS"
id = "47bc476c9bb04bdea4a4eb5424122e60"
preview_id = "fbffca54ee214babb24f933f7873c772"